version: '3'

networks:
  app_network:
    external: true

services:
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    ports:
      - "5000:5000"

  consumer1:
    build:
      context: ./consumer1
      dockerfile: Dockerfile
    container_name: consumer1
    
    
  consumer2:
    build:
      context: ./consumer2
      dockerfile: Dockerfile
    container_name: consumer2
    
  consumer3:
    build:
      context: ./consumer3
      dockerfile: Dockerfile
    container_name: consumer3
    

  consumer4:
    build:
      context: ./consumer4
      dockerfile: Dockerfile
    container_name: consumer4
    
    